language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

install:
  - cd ./backend && npm install && cd ..
  - cd ./frontend && npm install && cd ..

before_script:
  - cd ./backend && npm run test && cd ..
  - cd ./frontend && npm run lint && cd ..

script:
  - ./build.sh
  - docker images | grep foolifish07
  - echo $DOCKER_USERNAME

# https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/letstalk;
    fi

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules