language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

before_install:
  - pwd
  - docker info

after_install:
  - echo "after script"


before_script:
  - echo "before script"
  - pwd

script:
  - echo "script"
  - pwd

after_script:
  - echo "after script"

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules