language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

install:
  - cd ./backend && npm install && cd ..
  - cd ./frontend && npm install && cd ..

before_script:
  - cd ./backend && npm run test && cd ..

script:
  - ./build.sh
  - docker images | grep foolifish07
  - echo $DOCKER_USERNAME

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/letstalk;
    fi

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules