language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

install:
  - cd ./backend && npm install && cd ..
  - cd ./frontend && npm install && cd ..

before_script:
  - cd ./backend && npm run test && cd ..

script:
  - ./build.sh
  - docker images | grep foolifish07
  - docker push foolifish07/letstalk

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules