language: node_js

node_js:
- "7"
- "8"

sudo: required

services:
- docker

before_install:
- pwd
- sudo apt-get update
- sudo apt-get --yes --option Dpkg::Options::="--force-confnew" install docker-ce
- docker info

before_script:
  - NODE_ENV=test backend/node_modules/.mocha

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules